### PR TITLE
Support both python2 and python3 [#32]

### LINKED ISSUE #32: Python 3 compatibility
I was just asked by OctoPrint (v 1.4.0) today to do a Python 3 test (there is a new app for that) and report an issue to all plugin githubs that were found incompatible with Python 3 (if not already such an issue was stated).
Did the test and got back that the your plugin was Incompatible with Python 3 and could not find any other open issue about it - so here it is. :)

Cheers

### PR DESCRIPTION
**Pull request by bradcfisher**
Additional compatibility updates for Python 3 to address #32

### CODE REVIEW

**Comment by ruedli** [comment]
Thank you for your work. Is the upgrade downwards compatible, so may we expect the installed plugin to work with both Python 2 and Python 3? Will it be merged and then available through the normal plugin-repository?

**Comment by nxvash** [comment]
Any word on when python 3 compatibility will be available?

**Comment by pfsmorigo** [comment]
Looking forward for this support!

**Comment by cp2004** [comment]
Hey @bradcfisher, I'm looking into plugins that are not yet compatible with Python 3 across the repository - this plugin is the most popular plugin that has not yet become compatible.

Please can we get this moving, since [users want to be moving to Python 3](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/) and OctoPrint will drop support for Python 2 in the next year (2021) - your plugin will **no longer be usable for them**, and it has at least **5.82k** users running it.

I see that this is in progress, and if you would like some help doing this I am happy to give it a go - if you want to have a chat about it, you can find me on the [OctoPrint discord server](https://discord.octoprint.org) (as @cp2004) and we can look at what needs to be done, to get this plugin to Python 3 so it can continue to live as successfully as it has so far.

Thank you, and I hope to hear from you soon!

**Review by ira-at-work — APPROVED** [review]
LGTM
image

When can we expect a merge?

**Comment by pfsmorigo** [comment]
Hello. Please merge this request.

**Comment by ira-bv** [comment]
Until the maintainer finds the time to merge, I have done the following:

1. Uninstall the plugin on my octopi (plus any other non-python3-compatible plugins)
2. SSH to the RasPi, backup homedir and [do the described procedure](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/).
3. install this plugin with "install plugin from URL" but use the branch zip rather than the master: https://github.com/bradcfisher/OctoPrint-ExcludeRegionPlugin/archive/feature/python3_compat.zip
4. restart Octoprint
5. looking good!

**Review by cp2004 — APPROVED** [review]

**Comment by cp2004** [comment]
Users are continuing to migrate to Python 3, and this plugin does not work for them. @bradcfisher if you no longer have the time to maintain this plugin, I recommend putting it up for adoption and someone can either take over maintenance, or work on it with you to get this moving forwards.

**Comment by ira-bv** [comment]
@bradcfisher Thank you!!

**Pull request merged**
